server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    reactor:
      netty:
        http:
          client:
            HttpClient: DEBUG
    org:
      springframework:
        http:
          codec:
            json: TRACE
        web:
          reactive: TRACE
